// Master Orchestrator — entry point for the AI pipeline.
// Called by: .github/workflows/ai-agents.yml (on issue opened with "ai-task" label)
//
// Pipeline:
//   1. Parse GitHub issue
//   2. Create feature branch
//   3. Architect → docs/architecture.md + docs/tasks.md
//   4. Developer → src/ code files
//   5. Tester    → tests/ test files
//   6. git commit + push
//   7. Create PR via GitHub API
//   8. Post summary comment on the issue

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { postIssueComment, createPullRequest, addIssueLabels } = require('../../scripts/github');
const { run: runArchitect } = require('../architect');
const { run: runDeveloper } = require('../developer');
const { run: runTester } = require('../tester');

// ─── Helpers ────────────────────────────────────────────────────────────────

function exec(cmd, opts = {}) {
  console.log(`$ ${cmd}`);
  execSync(cmd, { stdio: 'inherit', ...opts });
}

function writeFiles(files) {
  for (const { filePath, content } of files) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`  wrote: ${filePath}`);
  }
}

function buildStatusTable(statuses) {
  const rows = statuses.map(([agent, status]) => `| ${agent} | ${status} |`).join('\n');
  return `| Agent | Status |\n|-------|--------|\n${rows}`;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  // 1. Read the GitHub event payload
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath) throw new Error('GITHUB_EVENT_PATH is not set');
  const event = JSON.parse(fs.readFileSync(eventPath, 'utf8'));

  const issue = event.issue;
  if (!issue) throw new Error('Event does not contain an issue');

  const { number: issueNumber, title: issueTitle, body: issueBody = '' } = issue;
  const branchName = `feature/issue-${issueNumber}`;

  console.log(`\n🚀 AI Pipeline — Issue #${issueNumber}: ${issueTitle}\n`);

  // 2. Initial comment — pipeline starting
  await postIssueComment(issueNumber, [
    '## 🤖 AI Agent Pipeline — Starting',
    '',
    `**Issue:** ${issueTitle}`,
    '',
    buildStatusTable([
      ['🏗️  Architect', '⏳ Running…'],
      ['👨‍💻  Developer', '⏸️  Waiting'],
      ['🧪  Tester',     '⏸️  Waiting'],
      ['🔀  PR',         '⏸️  Waiting'],
    ]),
  ].join('\n'));

  // 3. Create the feature branch
  exec('git config user.name "AI Agent Bot"');
  exec('git config user.email "ai-agent-bot@users.noreply.github.com"');
  exec(`git checkout -b ${branchName}`);

  // 4. Architect agent
  console.log('\n── Architect ──');
  const { architectureMd, tasksMd } = await runArchitect(issueTitle, issueBody);
  fs.mkdirSync('docs', { recursive: true });
  fs.writeFileSync('docs/architecture.md', architectureMd, 'utf8');
  fs.writeFileSync('docs/tasks.md', tasksMd, 'utf8');
  console.log('Architect: docs/architecture.md + docs/tasks.md written.');

  // 5. Developer agent
  console.log('\n── Developer ──');
  const sourceFiles = await runDeveloper(issueTitle, issueBody, architectureMd, tasksMd);
  writeFiles(sourceFiles);
  console.log(`Developer: ${sourceFiles.length} file(s) written.`);

  // 6. Tester agent
  console.log('\n── Tester ──');
  const testFiles = await runTester(issueTitle, issueBody, sourceFiles);
  writeFiles(testFiles);
  console.log(`Tester: ${testFiles.length} file(s) written.`);

  // 7. Commit and push
  console.log('\n── Git ──');
  exec('git add docs/ src/ tests/');
  exec(
    `git commit -m "feat(ai): implement #${issueNumber} — ${issueTitle}\n\nGenerated by AI Multi-Agent Pipeline"`,
    { shell: true }
  );
  exec(`git push origin ${branchName}`);

  // 8. Create PR
  console.log('\n── Pull Request ──');
  const sourceList = sourceFiles.map(f => `- \`${f.filePath}\``).join('\n');
  const testList   = testFiles.map(f => `- \`${f.filePath}\``).join('\n');

  const pr = await createPullRequest({
    head: branchName,
    title: `feat: ${issueTitle}`,
    body: [
      `## AI-Generated Feature`,
      '',
      `Closes #${issueNumber}`,
      '',
      '### Generated source files',
      sourceList || '_none_',
      '',
      '### Generated test files',
      testList || '_none_',
      '',
      '---',
      '### Architecture summary',
      architectureMd.split('\n').slice(0, 30).join('\n'),
      '',
      '_Opened automatically by the AI Multi-Agent Pipeline_ 🤖',
    ].join('\n'),
  });

  await addIssueLabels(issueNumber, ['ai-generated']);

  // 9. Final summary comment
  await postIssueComment(issueNumber, [
    '## ✅ AI Agent Pipeline — Complete',
    '',
    buildStatusTable([
      ['🏗️  Architect', '✅ Done'],
      ['👨‍💻  Developer', `✅ ${sourceFiles.length} file(s)`],
      ['🧪  Tester',     `✅ ${testFiles.length} file(s)`],
      ['🔀  PR',         `✅ [PR #${pr.number}](${pr.html_url})`],
    ]),
    '',
    `**Branch:** \`${branchName}\``,
    '',
    '> 🔍 The PR Review agent will post a code review shortly.',
  ].join('\n'));

  console.log(`\n✅ Done. PR: ${pr.html_url}`);
}

main().catch(err => {
  console.error('\n❌ Orchestrator failed:', err);
  process.exit(1);
});
